services:
  mariadb-wira:
    build:
      context: .
      dockerfile: mariadb.Containerfile
    container_name: mariadb-wira
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: showroom_mobil
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql:Z

  php-apache-wira:
    build:
      context: .
      dockerfile: php-apache.Containerfile
    container_name: php-apache-wira
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/html:Z
    depends_on:
      - mariadb-wira

  phpmyadmin-wira:
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: phpmyadmin-wira
    restart: always
    ports:
      - "8002:80"
    environment:
      PMA_HOST: mariadb-wira
      MYSQL_ROOT_PASSWORD: 12341234
    depends_on:
      - mariadb-wira

volumes:
  mariadb-data: {}
